"""
Story panels API - serves panel sequences for the visual novel experience.

Uses panels generated by the constraint-based prompt system.
"""

from fastapi import APIRouter, HTTPException
from typing import Optional
import os
import time

# Import voice config
try:
    from story_voices import get_story_voice_config, get_panel_voice_config
except ImportError:
    get_story_voice_config = None
    get_panel_voice_config = None

router = APIRouter(prefix="/api/story-panels", tags=["story-panels"])

# Base URL for serving generated images
IMAGE_BASE_URL = "/images/generated"

# Panel data for Shogun story (Prologue + Chapter 1)
# All panels generated using constraint-based prompts with Nano Banana Pro
SHOGUN_STORY = {
    "id": "shogun_test",
    "title": "The Weight of Words",
    "subtitle": "Shogun Era, Japan 1600",
    "chapters": [
        {
            "id": "prologue",
            "title": "Prologue: The Ship",
            "panels": [
                {
                    "id": "pro_01_stars",
                    "image": f"{IMAGE_BASE_URL}/panels/prologue/pro_01_stars.png",
                    "aspect": "wide",
                    "narration": "You've been on this ship for three months. Or three years. Time moves strangely when you're running from something you can't name. The observation deck hums with a frequency just below hearing. Outside the curved window, stars drift like ash.",
                    "dialogue": None,
                    "speaker": None,
                },
                {
                    "id": "pro_02_bimbo_appears",
                    "image": f"{IMAGE_BASE_URL}/panels/prologue/pro_02_bimbo_appears.png",
                    "aspect": "square",
                    "narration": "Bimbo floats at the edge of your vision—your AI companion, a holographic figure trailing particles like thoughts half-formed. She's been with you since the beginning, teaching you languages through simulations. Safe practice. Controlled consequences.",
                    "dialogue": "You're not sleeping again.",
                    "speaker": "bimbo",
                },
                {
                    "id": "pro_02b_conversation",
                    "image": f"{IMAGE_BASE_URL}/panels/prologue/pro_02_bimbo_appears.png",
                    "aspect": "square",
                    "narration": None,
                    "dialogue": "The last simulation felt fake. I knew it wasn't real, so I didn't care. I was just... performing. I want real stakes.",
                    "speaker": "player",
                },
                {
                    "id": "pro_02c_warning",
                    "image": f"{IMAGE_BASE_URL}/panels/prologue/pro_03_decision.png",
                    "aspect": "square",
                    "narration": "Bimbo's light shifts, deepens. A long pause.",
                    "dialogue": "There's another mode. Full immersion. No safety markers. Your body will believe it's real. Pain will be real. Fear will be real. Death will feel like death.",
                    "speaker": "bimbo",
                },
                {
                    "id": "pro_03_decision",
                    "image": f"{IMAGE_BASE_URL}/panels/prologue/pro_03_decision.png",
                    "aspect": "square",
                    "narration": "You're already standing.",
                    "dialogue": "Where do we start?",
                    "speaker": "player",
                },
                {
                    "id": "pro_04_japan",
                    "image": f"{IMAGE_BASE_URL}/panels/prologue/pro_03_decision.png",
                    "aspect": "square",
                    "narration": None,
                    "dialogue": "Japan. 1600. The year before Sekigahara. A country eating itself. Warlords, samurai, peasants caught between. One wrong word could mean your head. Because you asked for stakes.",
                    "speaker": "bimbo",
                },
            ]
        },
        {
            "id": "ch01",
            "title": "Chapter 1: The Beach",
            "panels": [
                {
                    "id": "ch1_01_wake",
                    "image": f"{IMAGE_BASE_URL}/panels/ch01/ch1_01_wake.png",
                    "aspect": "wide",
                    "narration": "You wake with salt on your lips and sand in your wounds. The sky is the color of a bruise healing—purple and amber. Waves drag at your legs, lazy, indifferent to your survival. Your clothes are heavy, soaked—wool that doesn't belong to this century.",
                    "dialogue": None,
                    "speaker": None,
                },
                {
                    "id": "ch1_01b_memory",
                    "image": f"{IMAGE_BASE_URL}/panels/ch01/ch1_01_wake.png",
                    "aspect": "wide",
                    "narration": "Memory surfaces in fragments: the ship, the immersion chamber, Bimbo's voice saying 'full commitment means full disorientation.' You're a castaway now. A foreigner washed up on shores that have never welcomed foreigners.",
                    "dialogue": None,
                    "speaker": None,
                },
                {
                    "id": "ch1_02_farmers_approach",
                    "image": f"{IMAGE_BASE_URL}/panels/ch01/ch1_02_farmers_approach.png",
                    "aspect": "wide",
                    "narration": "Voices. You turn your head—pain lances through your neck, real and sharp—and see them coming down the beach. Four figures. Farmers, maybe, in simple clothes. One carries a hoe raised like a weapon. They're shouting words you don't understand.",
                    "dialogue": None,
                    "speaker": None,
                },
                {
                    "id": "ch1_03_time_freeze",
                    "image": f"{IMAGE_BASE_URL}/panels/ch01/ch1_03_time_freeze.png",
                    "aspect": "tall",
                    "narration": "The world stops. Waves hang suspended, white foam frozen mid-curl. The farmers are statues, mouths open, arms raised in alarm or threat—you can't tell which. Bimbo's voice, close and calm:",
                    "dialogue": None,
                    "speaker": None,
                },
                {
                    "id": "ch1_04_bimbo_teaches",
                    "image": f"{IMAGE_BASE_URL}/panels/ch01/ch1_04_bimbo_teaches.png",
                    "aspect": "square",
                    "narration": None,
                    "dialogue": "I froze time. I can do that when you need to think. They're asking who you are. You need to answer—and how you answer matters.",
                    "speaker": "bimbo",
                    "effect": "time_freeze",
                    "options": [
                        {
                            "text": "Identify as castaway",
                            "style": "humble",
                            "next_scenario": None,
                            "examples": [
                                {
                                    "native": "I am a castaway",
                                    "target": "私は漂流者です",
                                    "pronunciation": "Watashi wa hyouryuusha desu"
                                }
                            ]
                        },
                        {
                            "text": "Plead for help",
                            "style": "desperate",
                            "next_scenario": None,
                            "examples": [
                                {
                                    "native": "Please help me",
                                    "target": "助けてください",
                                    "pronunciation": "Tasukete kudasai"
                                }
                            ]
                        },
                        {
                            "text": "Ask who they are",
                            "style": "bold",
                            "next_scenario": None,
                            "examples": [
                                {
                                    "native": "Who are you?",
                                    "target": "あなたは誰ですか",
                                    "pronunciation": "Anata wa dare desu ka"
                                }
                            ]
                        }
                    ]
                },
                {
                    "id": "ch1_04b_explain",
                    "image": f"{IMAGE_BASE_URL}/panels/ch01/ch1_04_bimbo_teaches.png",
                    "aspect": "square",
                    "narration": None,
                    "dialogue": "Good choice. 'Hyouryuusha'—castaway. It marks you as a victim, not an intruder. Say it clearly. Your life depends on it.",
                    "speaker": "bimbo",
                    "choice_variants": {
                        "ch1_04_bimbo_teaches": {
                            "0": {
                                "dialogue": "Good choice. 'Hyouryuusha'—castaway. It marks you as a victim, not an intruder. Say it clearly. Your life depends on it."
                            },
                            "1": {
                                "dialogue": "'Tasukete kudasai'—please help me. Desperation is honest. They'll see you're no threat. Say it like you mean it."
                            },
                            "2": {
                                "dialogue": "Bold. 'Anata wa dare desu ka'—who are you? It shows courage, but be careful. Too much confidence from a stranger can look like arrogance."
                            }
                        }
                    },
                },
                {
                    "id": "ch1_05_time_resumes",
                    "image": f"{IMAGE_BASE_URL}/panels/ch01/ch1_05_time_resumes.png",
                    "aspect": "tall",
                    "narration": "Time crashes back into motion. The farmers rush toward you, the one with the hoe raising it high. Your heart hammers. This is real. Bimbo warned you—the fear would be real.",
                    "dialogue": None,
                    "speaker": None,
                    "effect": "time_resume",
                },
                {
                    "id": "ch1_06_speak",
                    "image": f"{IMAGE_BASE_URL}/panels/ch01/ch1_06_speak.png",
                    "aspect": "square",
                    "narration": "You scramble back, hands up in surrender. The words tumble out—clumsy, desperate, but the right words:",
                    "dialogue": "Watashi wa hyouryuusha desu!",
                    "speaker": "player",
                    "choice_variants": {
                        "ch1_04_bimbo_teaches": {
                            "0": {
                                "dialogue": "Watashi wa hyouryuusha desu!"
                            },
                            "1": {
                                "narration": "You drop to your knees, hands clasped. The words pour out—raw, desperate:",
                                "dialogue": "Tasukete kudasai!"
                            },
                            "2": {
                                "narration": "You stand your ground, meeting their eyes. The words come out steady, almost defiant:",
                                "dialogue": "Anata wa dare desu ka?"
                            }
                        }
                    },
                },
                {
                    "id": "ch1_06b_stop",
                    "image": f"{IMAGE_BASE_URL}/panels/ch01/ch1_06_speak.png",
                    "aspect": "square",
                    "narration": "They stop. The man with the hoe hesitates. The others exchange glances. Your first words in this world, and they didn't get you killed.",
                    "dialogue": None,
                    "speaker": None,
                },
                {
                    "id": "ch1_07_hana_steps",
                    "image": f"{IMAGE_BASE_URL}/panels/ch01/ch1_07_hana_steps.png",
                    "aspect": "square",
                    "narration": "One woman—older, face weathered like driftwood—steps forward. She studies you with sharp eyes. Then speaks slowly, as if to a child:",
                    "dialogue": "Doko kara?",
                    "speaker": "hana",
                },
                {
                    "id": "ch1_08_freeze_doko",
                    "image": f"{IMAGE_BASE_URL}/panels/ch01/ch1_08_freeze_doko.png",
                    "aspect": "square",
                    "narration": "Time freezes again. Bimbo appears beside you.",
                    "dialogue": "She's asking where you came from. Be careful—mentioning Portugal, Spain, or England could mark you as a Christian missionary. They're being hunted.",
                    "speaker": "bimbo",
                    "effect": "time_freeze",
                    "options": [
                        {
                            "text": "From the sea",
                            "style": "safe",
                            "next_scenario": None,
                            "examples": [
                                {
                                    "native": "From the sea",
                                    "target": "海から",
                                    "pronunciation": "Umi kara"
                                }
                            ]
                        },
                        {
                            "text": "From far away",
                            "style": "vague",
                            "next_scenario": None,
                            "examples": [
                                {
                                    "native": "From far away",
                                    "target": "遠くから",
                                    "pronunciation": "Tooku kara"
                                }
                            ]
                        },
                        {
                            "text": "From a ship",
                            "style": "honest",
                            "next_scenario": None,
                            "examples": [
                                {
                                    "native": "From a ship",
                                    "target": "船から",
                                    "pronunciation": "Fune kara"
                                }
                            ]
                        }
                    ]
                },
                {
                    "id": "ch1_09_umi_kara",
                    "image": f"{IMAGE_BASE_URL}/panels/ch01/ch1_09_umi_kara.png",
                    "aspect": "square",
                    "narration": "Time resumes. You gesture at the waves behind you.",
                    "dialogue": "Umi kara.",
                    "speaker": "player",
                    "choice_variants": {
                        "ch1_08_freeze_doko": {
                            "0": {
                                "dialogue": "Umi kara."
                            },
                            "1": {
                                "narration": "Time resumes. You sweep your hand toward the horizon.",
                                "dialogue": "Tooku kara."
                            },
                            "2": {
                                "narration": "Time resumes. You point out at the water, toward a shape that might be wreckage.",
                                "dialogue": "Fune kara."
                            }
                        }
                    },
                },
                {
                    "id": "ch1_09b_nod",
                    "image": f"{IMAGE_BASE_URL}/panels/ch01/ch1_09_umi_kara.png",
                    "aspect": "square",
                    "narration": "The woman nods slowly. She turns to the others and speaks rapidly—too fast for you to catch anything. But you hear one word repeated: 'sama.' An honorific. She's talking about someone important.",
                    "dialogue": None,
                    "speaker": None,
                },
                {
                    "id": "ch1_10_kite",
                    "image": f"{IMAGE_BASE_URL}/panels/ch01/ch1_10_kite.png",
                    "aspect": "wide",
                    "narration": "When she turns back, her expression has changed. Not softer, exactly. But resolved. She gestures for you to follow.",
                    "dialogue": "Kite.",
                    "speaker": "hana",
                },
                {
                    "id": "ch1_10b_end",
                    "image": f"{IMAGE_BASE_URL}/panels/ch01/ch1_10_kite.png",
                    "aspect": "wide",
                    "narration": "You have no choice. You follow. Your first lesson is complete: in this world, the right words can save your life. The wrong ones can end it.",
                    "dialogue": None,
                    "speaker": None,
                },
            ]
        }
    ]
}

# Story registry
STORIES = {
    "shogun_test": SHOGUN_STORY,
}


@router.get("/stories")
async def list_stories():
    """List available stories."""
    return {
        "stories": [
            {
                "id": story["id"],
                "title": story["title"],
                "subtitle": story.get("subtitle"),
                "chapter_count": len(story["chapters"]),
            }
            for story in STORIES.values()
        ]
    }


@router.get("/stories/{story_id}")
async def get_story(story_id: str):
    """Get full story with all chapters and panels."""
    story = STORIES.get(story_id)
    if not story:
        raise HTTPException(status_code=404, detail="Story not found")
    return story


@router.get("/stories/{story_id}/chapters/{chapter_id}")
async def get_chapter(story_id: str, chapter_id: str):
    """Get a specific chapter."""
    story = STORIES.get(story_id)
    if not story:
        raise HTTPException(status_code=404, detail="Story not found")

    for chapter in story["chapters"]:
        if chapter["id"] == chapter_id:
            return chapter

    raise HTTPException(status_code=404, detail="Chapter not found")


@router.get("/stories/{story_id}/voice-config")
async def get_voice_config(story_id: str):
    """Get voice configuration for a story."""
    if not get_story_voice_config:
        return {"error": "Voice config not available"}

    config = get_story_voice_config(story_id)
    if not config:
        # Return defaults
        return {
            "story_id": story_id,
            "narrator": {
                "voice": "alloy",
                "style": "Speak with calm authority.",
            },
            "characters": {},
        }

    return {
        "story_id": config.story_id,
        "narrator": {
            "voice": config.narrator_voice,
            "style": config.narrator_style,
        },
        "characters": {
            char_id: {
                "voice": char.voice,
                "gender": char.gender,
                "sentiment": char.default_sentiment,
                "style": char.speaking_style,
            }
            for char_id, char in config.characters.items()
        },
    }


@router.get("/stories/{story_id}/panels/{panel_id}/voice")
async def get_panel_voice(story_id: str, panel_id: str):
    """Get voice config for a specific panel."""
    story = STORIES.get(story_id)
    if not story:
        raise HTTPException(status_code=404, detail="Story not found")

    # Find the panel
    panel = None
    for chapter in story["chapters"]:
        for p in chapter["panels"]:
            if p["id"] == panel_id:
                panel = p
                break
        if panel:
            break

    if not panel:
        raise HTTPException(status_code=404, detail="Panel not found")

    if not get_panel_voice_config:
        return {"panel_id": panel_id, "narration": None, "dialogue": None}

    config = get_panel_voice_config(story_id, panel)
    return {"panel_id": panel_id, **config}
